spring:
  datasource:
    jdbc-url: 'jdbc:postgresql://195.150.230.208:5432/2023_nowak_kajetan'
    username: '2023_nowak_kajetan'
    password: '35686'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format-sql: true
